//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKTX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DKPhong
    {
        public int DKPhongID { get; set; }
        public Nullable<int> SinhVienID { get; set; }
        public Nullable<int> PhongID { get; set; }
        public Nullable<System.DateTime> NgayDK { get; set; }
        public Nullable<System.DateTime> NgayTra { get; set; }
    
        public virtual Phong Phong { get; set; }
        public virtual SinhVien SinhVien { get; set; }
    }
}
