//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKTX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Phong()
        {
            this.DienNuocs = new HashSet<DienNuoc>();
            this.DKPhongs = new HashSet<DKPhong>();
            this.HoaDons = new HashSet<HoaDon>();
        }
    
        public int PhongID { get; set; }
        public Nullable<int> ToaNhaID { get; set; }
        public Nullable<int> LoaiPhongID { get; set; }
        public string TenPhong { get; set; }
        public string TinhTrang { get; set; }
        public Nullable<int> SoLuongGiuong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DienNuoc> DienNuocs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DKPhong> DKPhongs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons { get; set; }
        public virtual LoaiPhong LoaiPhong { get; set; }
        public virtual ToaNha ToaNha { get; set; }
    }
}
